# Generated by Django 5.1.7 on 2025-03-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('color_id', models.PositiveIntegerField()),
                ('size_id', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
            options={
                'unique_together': {('product_id', 'color_id', 'size_id')},
            },
        ),
    ]
